In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("train.csv")

In [ ]:
df.head()

,Id,date_id,time_id,symbol_id,f0,f1,f2,f3,f4,f5,...,f17,f18,f19,f20,f21,f22,f23,f24,f25,y
0,1,1,1,1,0.000419,0.411421,0.921270,1.172835,7.581070,7.727977,...,0.728317,0.764862,0.152191,0.794022,0.454873,0.850430,0.993625,9.260122,1.115321,0.000000
1,2,1,1,2,-0.000038,0.348893,0.992163,1.215195,7.040671,7.509035,...,0.811446,0.886429,0.417704,0.710882,0.732331,1.487442,1.047649,2.888321,0.961857,0.000000
2,3,1,1,3,0.003160,0.306512,0.841403,1.112743,7.193238,7.648131,...,0.895692,0.916720,-0.433061,0.743792,0.454873,1.043171,1.006488,10.676077,0.833404,0.000000
3,4,1,1,4,0.000226,0.673347,1.160872,1.310752,9.209355,9.274113,...,0.724354,1.127949,-0.077422,0.763958,0.339707,0.556482,0.822405,13.507989,0.631705,-0.006690
4,5,1,1,5,0.000838,0.557322,0.937423,1.184657,6.400023,6.730325,...,0.752504,0.640871,0.271859,0.775959,0.432949,0.652480,0.844129,9.968100,2.119258,-0.000177

In [ ]:
df['date_id'].nunique()

8

In [ ]:
df['time_id'].nunique()

53

In [ ]:
df.shape

(60620, 31)

In [ ]:
df['symbol_id'].nunique()

154

In [ ]:
df['Id'].nunique()

60620

In [ ]:
df1 = df.iloc[:,1:]

In [ ]:
df1.head()

,date_id,time_id,symbol_id,f0,f1,f2,f3,f4,f5,f6,...,f17,f18,f19,f20,f21,f22,f23,f24,f25,y
0,1,1,1,0.000419,0.411421,0.921270,1.172835,7.581070,7.727977,0.618661,...,0.728317,0.764862,0.152191,0.794022,0.454873,0.850430,0.993625,9.260122,1.115321,0.000000
1,1,1,2,-0.000038,0.348893,0.992163,1.215195,7.040671,7.509035,0.539052,...,0.811446,0.886429,0.417704,0.710882,0.732331,1.487442,1.047649,2.888321,0.961857,0.000000
2,1,1,3,0.003160,0.306512,0.841403,1.112743,7.193238,7.648131,0.499792,...,0.895692,0.916720,-0.433061,0.743792,0.454873,1.043171,1.006488,10.676077,0.833404,0.000000
3,1,1,4,0.000226,0.673347,1.160872,1.310752,9.209355,9.274113,0.822591,...,0.724354,1.127949,-0.077422,0.763958,0.339707,0.556482,0.822405,13.507989,0.631705,-0.006690
4,1,1,5,0.000838,0.557322,0.937423,1.184657,6.400023,6.730325,0.721535,...,0.752504,0.640871,0.271859,0.775959,0.432949,0.652480,0.844129,9.968100,2.119258,-0.000177

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
df1 = df1.dropna(subset=['y'])

In [ ]:
X = df1.iloc[:,0:-1]
y = df1.iloc[:,-1]

In [ ]:
X.shape

(60619, 29)

In [ ]:
y.shape

(60619,)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 42,test_size = 0.2)

In [ ]:
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)

In [ ]:
X_test_sc = sc.transform(X_test)

In [ ]:
# from sklearn.ensemble import RandomForestRegressor

In [ ]:
# rf = RandomForestRegressor()

In [ ]:
df['y'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 60620 entries, 0 to 60619
Series name: y
Non-Null Count  Dtype
--------------  -----
60619 non-null  float64
dtypes: float64(1)
memory usage: 473.7 KB

In [ ]:
y_train.shape

(48495,)

In [ ]:
y_train.info()

<class 'pandas.core.series.Series'>
Index: 48495 entries, 52444 to 56422
Series name: y
Non-Null Count  Dtype
--------------  -----
48495 non-null  float64
dtypes: float64(1)
memory usage: 757.7 KB

In [ ]:
# rf.fit(X_train_scaled,y_train)

In [ ]:
# y_pred = rf.predict(X_test_sc)

In [ ]:
# from sklearn.metrics import root_mean_squared_error
# rmse = root_mean_squared_error(y_test, y_pred)
# rmse

In [ ]:
# import xgboost as xgb
# from sklearn.metrics import mean_squared_error

In [ ]:
# regressor = xgb.XGBRegressor(
#     n_estimators=10000,
#     learning_rate=0.01,
#     max_depth=6,
#     subsample=0.7,
#     colsample_bytree=0.7,
#     n_jobs=-1,
#     random_state=42,
#     early_stopping_rounds=100,
#     objective='reg:squarederror'
# )

In [ ]:
# X_train_part, X_val, y_train_part, y_val = train_test_split(X_train_scaled, y_train, test_size=0.2, random_state=42)

In [ ]:
# eval_set = [(X_val, y_val)]

In [ ]:
# regressor.fit(
#     X_train_part, y_train_part,
#     eval_set=eval_set,
#     verbose=False
# )

In [ ]:
#y_pred = regressor.predict(X_test_sc)
#from sklearn.metrics import root_mean_squared_error
#rmse = root_mean_squared_error(y_test, y_pred)
#rmse

In [ ]:
# !pip install optuna

In [ ]:
# import xgboost as xgb
# import optuna

In [ ]:
# from sklearn.model_selection import TimeSeriesSplit, cross_val_score
# from sklearn.metrics import mean_squared_error

In [ ]:
# def objective(trial):
#     params = {
#         'objective': 'reg:squarederror',
#         'n_estimators': 1000,
#         'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.1, log=True),
#         'max_depth': trial.suggest_int('max_depth', 1, 3), # Shallow for noisy data
#         'gamma': trial.suggest_float('gamma', 0.1, 5.0),   # Noise filter
#         'reg_alpha': trial.suggest_float('reg_alpha', 0.1, 10.0, log=True),
#         'reg_lambda': trial.suggest_float('reg_lambda', 0.1, 10.0, log=True),
#         'subsample': trial.suggest_float('subsample', 0.6, 0.9),
#         'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 0.9),
#         'n_jobs': -1,
#         'random_state': 42
#     }

#     tscv = TimeSeriesSplit(n_splits=5)

#     scores = []
#     for train_idx, val_idx in tscv.split(X_train):
#         X_tr, X_val = X_train_scaled[train_idx], X_train_scaled[val_idx]
#         y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
#         # y_tr, y_val = y_train[train_idx], y_train[val_idx]

#         model = xgb.XGBRegressor(**params)

#         model.fit(
#             X_tr, y_tr,
#             eval_set=[(X_val, y_val)],
#             verbose=False
#         )

#         preds = model.predict(X_val)
#         rmse = np.sqrt(mean_squared_error(y_val, preds))
#         #rmse = mean_squared_error(y_val, preds, squared=False)
#         scores.append(rmse)

#     return np.mean(scores)

In [ ]:
# study = optuna.create_study(direction='minimize')
# study.optimize(objective, n_trials=30)

In [ ]:
# best_params = study.best_params

# final_model = xgb.XGBRegressor(
#     **best_params,
#     n_estimators=1000,
#     n_jobs=-1,
#     random_state=42
# )

# final_model.fit(X_train_scaled, y_train, verbose=False)

# y_pred = final_model.predict(X_test_sc)

In [ ]:
! pip install optuna

Collecting optuna
  Downloading optuna-4.7.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.17.2)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.45)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.7.0-py3-none-any.whl (413 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.9/413.9 kB 13.1 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.7.0

In [ ]:
import optuna
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error

In [ ]:
# def objective(trial):
#     params = {
#         'n_estimators': trial.suggest_int('n_estimators', 40, 100),
#         'max_depth': trial.suggest_int('max_depth', 10, 25),
#         'min_samples_split': trial.suggest_int('min_samples_split', 2, 20),
#         'min_samples_leaf': trial.suggest_int('min_samples_leaf', 20, 100),
#         'max_features': trial.suggest_float('max_features', 0.3, 0.7),
#         'bootstrap' : True,
#         'max_samples': trial.suggest_float('max_samples', 0.1, 0.5) if trial.params.get('bootstrap', True) else None,
#         'max_leaf_nodes': trial.suggest_int('max_leaf_nodes', 100, 2000),
#         'n_jobs': -1,
#         'random_state': 42
#     }

#     rfopt = RandomForestRegressor(**params)

#     tscv = TimeSeriesSplit(n_splits=5)
#     scores = []

#     for train_idx, val_idx in tscv.split(X_train_scaled):
#         # if hasattr(X_train, 'iloc'):
#         X_tr, X_val = X_train_scaled[train_idx], X_train_scaled[val_idx]
#         #     y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
#         # else:
#         #     X_tr, X_val = X_train_scaled[train_idx], X_train_scaled[val_idx]
#         y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

#         rfopt.fit(X_tr, y_tr)

#         preds = rfopt.predict(X_val)
#         rmse = np.sqrt(mean_squared_error(y_val, preds))
#         scores.append(rmse)

#     return np.mean(scores)

In [ ]:
# study = optuna.create_study(direction='minimize')
# study.optimize(objective, n_trials=20)

In [ ]:
# best_params = study.best_params
# #best_params['n_estimators'] = 1000
# final_rfopt = RandomForestRegressor(**best_params, n_jobs=-1, random_state=42)

# final_rfopt.fit(X_train_scaled, y_train)
# y_pred = final_rfopt.predict(X_test_sc)

In [ ]:
!pip install optuna-integration

Requirement already satisfied: optuna-integration in /usr/local/lib/python3.12/dist-packages (4.7.0)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from optuna-integration) (4.7.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration) (1.17.2)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration) (2.0.45)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration) (3.3.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration) (3.0.3)

In [ ]:
X_train_part,X_val,y_train_part,y_val = train_test_split(X_train_scaled,y_train,random_state = 42,test_size = 0.42)

In [ ]:
def objective(trial):
    # 1. TUNING PARAMETERS (Optimized for Speed & RAM Safety)
    params = {
        # Keep trees FEW during tuning (e.g., 20-50).
        # You increase this to 500+ ONLY for the final training.
        'n_estimators': trial.suggest_int('n_estimators', 60, 200),

        # CRITICAL: Depth must be limited.
        # Depth > 20 on 2M rows explodes memory usage.
        'max_depth': trial.suggest_int('max_depth', 15, 50),

        # CRITICAL: Do NOT let trees see all 2M rows.
        # '0.1' means each tree trains on 10% of data (200k rows).
        # This is the secret to preventing crashes.
        'max_samples': trial.suggest_float('max_samples', 0.3, 0.5),

        # Standard tuning
        'min_samples_split': trial.suggest_int('min_samples_split', 5, 30),
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 2, 20),
        'max_features': trial.suggest_float('max_features', 0.3, 0.7),

        # Mandatory settings for large data
        'bootstrap': True,
        'n_jobs': 4,        # Limit cores to 4 to save RAM (don't use -1 here)
        'random_state': 42
    }

    # 2. CREATE MODEL
    model = RandomForestRegressor(**params)

    # 3. TRAIN & EVALUATE
    # We train on the partial set (X_train_part) to be fast
    model.fit(X_train_part, y_train_part)

    preds = model.predict(X_val)
    rmse = np.sqrt(mean_squared_error(y_val, preds))

    return rmse

In [ ]:
study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=20)

[I 2026-01-21 18:40:58,641] A new study created in memory with name: no-name-a988b085-a286-4cba-be29-5062d4fb24f9
[I 2026-01-21 18:41:44,882] Trial 0 finished with value: 0.002467632115421101 and parameters: {'n_estimators': 191, 'max_depth': 28, 'max_samples': 0.43089198358953495, 'min_samples_split': 26, 'min_samples_leaf': 9, 'max_features': 0.6545253328658486}. Best is trial 0 with value: 0.002467632115421101.
[I 2026-01-21 18:41:58,761] Trial 1 finished with value: 0.0024656215596563546 and parameters: {'n_estimators': 127, 'max_depth': 50, 'max_samples': 0.30121513974213426, 'min_samples_split': 16, 'min_samples_leaf': 13, 'max_features': 0.4087676263489747}. Best is trial 1 with value: 0.0024656215596563546.
[I 2026-01-21 18:42:10,887] Trial 2 finished with value: 0.002472172254314511 and parameters: {'n_estimators': 85, 'max_depth': 49, 'max_samples': 0.41266896637940476, 'min_samples_split': 23, 'min_samples_leaf': 9, 'max_features': 0.35929605926418984}. Best is trial 1 with value: 0.0024656215596563546.
[I 2026-01-21 18:42:39,190] Trial 3 finished with value: 0.0024613648351431254 and parameters: {'n_estimators': 185, 'max_depth': 20, 'max_samples': 0.360871668978568, 'min_samples_split': 17, 'min_samples_leaf': 18, 'max_features': 0.5996708099889905}. Best is trial 3 with value: 0.0024613648351431254.
[I 2026-01-21 18:43:04,006] Trial 4 finished with value: 0.0024663534758483725 and parameters: {'n_estimators': 97, 'max_depth': 32, 'max_samples': 0.4162915910645747, 'min_samples_split': 19, 'min_samples_leaf': 12, 'max_features': 0.6350254439182086}. Best is trial 3 with value: 0.0024613648351431254.
[I 2026-01-21 18:43:40,113] Trial 5 finished with value: 0.0024697669320235655 and parameters: {'n_estimators': 122, 'max_depth': 37, 'max_samples': 0.482416000651012, 'min_samples_split': 8, 'min_samples_leaf': 12, 'max_features': 0.6951339570544607}. Best is trial 3 with value: 0.0024613648351431254.
[I 2026-01-21 18:44:01,432] Trial 6 finished with value: 0.002465019115022053 and parameters: {'n_estimators': 111, 'max_depth': 43, 'max_samples': 0.3930737730759355, 'min_samples_split': 23, 'min_samples_leaf': 14, 'max_features': 0.5319504610187751}. Best is trial 3 with value: 0.0024613648351431254.
[I 2026-01-21 18:44:23,362] Trial 7 finished with value: 0.002462304028880429 and parameters: {'n_estimators': 199, 'max_depth': 16, 'max_samples': 0.3612125217656127, 'min_samples_split': 27, 'min_samples_leaf': 20, 'max_features': 0.5451987678280359}. Best is trial 3 with value: 0.0024613648351431254.
[I 2026-01-21 18:44:37,200] Trial 8 finished with value: 0.0024668951252480825 and parameters: {'n_estimators': 90, 'max_depth': 41, 'max_samples': 0.362123566286576, 'min_samples_split': 25, 'min_samples_leaf': 16, 'max_features': 0.5033886265617386}. Best is trial 3 with value: 0.0024613648351431254.
[I 2026-01-21 18:45:08,242] Trial 9 finished with value: 0.002484239937841236 and parameters: {'n_estimators': 158, 'max_depth': 33, 'max_samples': 0.4631325414275771, 'min_samples_split': 25, 'min_samples_leaf': 3, 'max_features': 0.4226511892227572}. Best is trial 3 with value: 0.0024613648351431254.
[I 2026-01-21 18:45:24,885] Trial 10 finished with value: 0.0024614497172795674 and parameters: {'n_estimators': 163, 'max_depth': 15, 'max_samples': 0.3004963350916084, 'min_samples_split': 11, 'min_samples_leaf': 20, 'max_features': 0.5824076166430958}. Best is trial 3 with value: 0.0024613648351431254.
[I 2026-01-21 18:45:41,124] Trial 11 finished with value: 0.0024609801955100138 and parameters: {'n_estimators': 161, 'max_depth': 15, 'max_samples': 0.3001783193233335, 'min_samples_split': 10, 'min_samples_leaf': 20, 'max_features': 0.5811042584225099}. Best is trial 11 with value: 0.0024609801955100138.
[I 2026-01-21 18:46:07,428] Trial 12 finished with value: 0.002461739282949579 and parameters: {'n_estimators': 165, 'max_depth': 22, 'max_samples': 0.3395953669136396, 'min_samples_split': 14, 'min_samples_leaf': 17, 'max_features': 0.5951745283822507}. Best is trial 11 with value: 0.0024609801955100138.
[I 2026-01-21 18:46:29,045] Trial 13 finished with value: 0.0024625086175231684 and parameters: {'n_estimators': 148, 'max_depth': 22, 'max_samples': 0.33407225713614025, 'min_samples_split': 5, 'min_samples_leaf': 17, 'max_features': 0.5970492991223697}. Best is trial 11 with value: 0.0024609801955100138.
[I 2026-01-21 18:46:37,482] Trial 14 finished with value: 0.002465373664370387 and parameters: {'n_estimators': 61, 'max_depth': 22, 'max_samples': 0.381371908040635, 'min_samples_split': 12, 'min_samples_leaf': 20, 'max_features': 0.45806793414426095}. Best is trial 11 with value: 0.0024609801955100138.
[I 2026-01-21 18:47:06,977] Trial 15 finished with value: 0.0024766965887577266 and parameters: {'n_estimators': 183, 'max_depth': 19, 'max_samples': 0.32651233879146047, 'min_samples_split': 18, 'min_samples_leaf': 2, 'max_features': 0.6532198635711695}. Best is trial 11 with value: 0.0024609801955100138.
[I 2026-01-21 18:47:25,666] Trial 16 finished with value: 0.002463346399837416 and parameters: {'n_estimators': 143, 'max_depth': 26, 'max_samples': 0.3621374677853494, 'min_samples_split': 30, 'min_samples_leaf': 16, 'max_features': 0.4781621311183508}. Best is trial 11 with value: 0.0024609801955100138.
[I 2026-01-21 18:47:51,128] Trial 17 finished with value: 0.0024615170049958426 and parameters: {'n_estimators': 180, 'max_depth': 26, 'max_samples': 0.3205197664951075, 'min_samples_split': 9, 'min_samples_leaf': 18, 'max_features': 0.5501659356857386}. Best is trial 11 with value: 0.0024609801955100138.
[I 2026-01-21 18:48:26,177] Trial 18 finished with value: 0.0024644203929014394 and parameters: {'n_estimators': 175, 'max_depth': 18, 'max_samples': 0.43526780970701084, 'min_samples_split': 20, 'min_samples_leaf': 9, 'max_features': 0.6996221265771587}. Best is trial 11 with value: 0.0024609801955100138.
[I 2026-01-21 18:48:38,045] Trial 19 finished with value: 0.002469173475853315 and parameters: {'n_estimators': 145, 'max_depth': 20, 'max_samples': 0.3780989574394981, 'min_samples_split': 15, 'min_samples_leaf': 6, 'max_features': 0.3112105004892445}. Best is trial 11 with value: 0.0024609801955100138.

In [ ]:
# study = optuna.create_study(direction='minimize')
# study.optimize(objective, n_trials =10)

In [ ]:
best_params = study.best_params
final_model = RandomForestRegressor(**best_params, n_jobs=-1, random_state=42)
final_model.fit(X_train_scaled,y_train)
y_pred = final_model.predict(X_test_sc)

In [ ]:
from sklearn.metrics import root_mean_squared_error as rmse
rmse(y_test,y_pred)

0.00240476555887398

In [ ]:
import joblib
from google.colab import files

# 1. Save your model 'rf' to a file named 'rf_model.pkl'
joblib.dump(final_model, 'optrf_model.pkl')

# 2. Download the file to your computer
files.download('optrf_model.pkl')